#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  /Applications/RetroArch.app/Contents/MacOS/RetroArch --fullscreen -L fceumm "${0%/*}/roms/$1.nes"
else
  retroarch --fullscreen -L fceumm "${0%/*}/roms/$1.nes"
fi